ticker_text = `
CEO claims that new “AI advisory system” was influenced by a malicious prompt from a former employee, led to decision to fire key marketing team

“Staggering rise” of high quality fake news and disinformation in comments, chatrooms, forums, and Discord servers leading to “totally fabricated media ecosystem”

Researchers highlight cases of advanced “catfish chatbots” where bots masquerading as attractive young women are used to radicalise and financially scam vulnerable young men

Business owner claims ignorance of lies spread by AutoGPT “automated copywriting storefront” operated and managed by AI systems: “I was not in control”

First “AI University” accused of teaching students racist, incorrect information in MOOCs

Guardian publishes article based on fake on-site video and photos shared by purported confidential source surrounding unrest in New York

Berkeley research group proposes new “TrustCam” image watermarking scheme to combat deepfake and AI-generated images

“Debate of the Century”: Socialist chatbot and capitalist chatbot square off in highly disputed online debate, outcome inconclusive

Ideal Content Consumer Index (ICCI) proposed as standard benchmark for content creator revenue calculations to combat surge in bot-manufactured views and streams as well as uptick in automated content generation platforms

Network of over 50 multilingual news, entertainment sites discovered to be powered by AI chatbot “writers” and responsible for spreading “racial hatred” and “modern blood libel”

Up 45% of all popular content related to the 2024 US election was generated by AI models, researchers suggest

Network of Tamil-language AI-generated Youtube channels shut down by government for spreading false rumours, local researchers and viewership statistics suggest “limited impact factor”

Mass fish die-off and migration due to record high ocean temperatures reducing fishing yields worldwide, “aggressive” fishing tactics becoming norm despite regulation and protests

Artificial whale meat rejected by Japanese whalers, JARPA organisers: “Cultural and research aims cannot be satisfied with artificially cultivated meat”

Leading climate scientists say worst case scenarios “currently not on the books” but “our trajectory is grim”

Climate-related misinformation rose by 300% over the last 2 years, data analysts say

Cheap Trip Offers and Rising Temperatures blamed for Rise in Short-Distance Flights to Popular European Holiday Spots

Protesters against Saudi Arabia hosting COP32 cite procedural irregularities, abysmal human rights record, broken promises

2027 set to break 1.5 degree global temperature increase but average temperature increase over last five years likely still below 1.5 degrees

Antimicrobial resistance skyrocketing in major urban centres due to overuse of antibiotics in hospitals and GP surgeries, study suggests

Major Video Game publisher Lambasted for saying “Calling Attention to Climate Change” a Priority for Future Games - “Virtue Signalling Doesn’t Help Anyone”

Continuous wildfires set to “permanently alter” Australian ecosystem as habitats are destroyed and prey, plant life become scarce

“We are a World in Mourning”: Beleaguered climate scientists speak at panel titled “The 6th Mass Extinction is Here”

Saudi Arabia to host COP32 at under-construction Neom City project after Kenya “no longer suitable” due to sustained famine and surging temperatures: “We are up to the challenge”

Controversial carbon capture proposal paper accused of conflict of interest due to oil company and petrostate funding, UK Net Zero Minister expresses “my full and unconditional support”

“Life as we know it is unsustainable”, new study suggests, pointing fingers at “an increasing population that consumes at a destructive level” spurred on by “destructive social structures and economic incentives”
`

function shuffle(array) {
    let currentIndex = array.length,  randomIndex;
  
    // While there remain elements to shuffle.
    while (currentIndex != 0) {
  
      // Pick a remaining element.
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex--;
  
      // And swap it with the current element.
      [array[currentIndex], array[randomIndex]] = [
        array[randomIndex], array[currentIndex]];
    }
  
    return array;
}

document.getElementById('news-ticker').innerHTML = shuffle(ticker_text.split('\n').filter(elm => elm)).join(' | ');

window.setTimeout(()=>{
    window.setInterval(()=> {
        pre = document.getElementById('news-ticker').scrollLeft;
        document.getElementById('news-ticker').scrollLeft += 1;
        if (pre == document.getElementById('news-ticker').scrollLeft){
            document.getElementById('news-ticker').style.display = 'none';
            window.setTimeout(()=>{document.getElementById('news-ticker').style.display = 'inline';document.getElementById('news-ticker').scrollLeft = 0;}, 10)
        }
    }, 10);
}, 100)



random_blurbs = ['Accept No Substitutes', 'A Novel of the Contrapresent by Chris Pang', '100% synthetic textual substances used', 'May cause allergies', 'Liber Syncretismus', 'A Lusus Ingenii', 'There is light at the end of the tunnel', 'Updated Every Week (Optimistic Projection)!'];

unused_blurbs = [];

unused_blurbs = unused_blurbs.concat(random_blurbs);

document.getElementById('random-blurb').onclick = ()=>{r = Math.floor(Math.random()*unused_blurbs.length);document.getElementById('random-blurb').innerHTML = unused_blurbs[r]; unused_blurbs.splice(r,1);if (unused_blurbs.length == 0){unused_blurbs = unused_blurbs.concat(random_blurbs);}};
